apiVersion: v1
kind: Service
metadata:
  name: nats-service
spec:
  ports:
    - port: 4222
      name: nats-client
      targetPort: 4222
      protocol: TCP
    - port: 8222
      name: nats-http
      targetPort: 6222
      protocol: TCP
    - port: 6222
      name: nats-route
      targetPort: 6222
      protocol: TCP
  selector:
      name: nats-services