apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
          - name: worker
            image: florian74/nats-worker:latest
            command:
              - 'main'
              - '-url'
              - 'nats://nats-service:4222'
              - '-name'
              - 'W1'
